# TOML Configuration File

title = "CFMS Configuration"

[general]
server_name = "CFMS Server"
locale = "zh_CN" # 语言代码

[connect]
ipv4_enabled = true
ipv6_enabled = false
ipv4_addr = "0.0.0.0"
ipv6_addr = ""

port = 5103

# 同时允许运行的 Handler 线程数与最大排队连接数。
# 总允许连接数 = max_handlers + max_queued_connections
max_handlers = 10
max_queued_connections = 3
# 这并不通常有效，因服务器将接受任何新的连接后在子线程中挂起它。

# 服务器应当以哪个端口开放 FTP 服务（文件传输所必需的）？
ftp_port = 5104

[security]
# 是否在每次启动时更新 token_secret ? 如果是，则重启服务后将导致所有 token 失效。
# 不更新适合于服务器在异常下线后重新启动。
update_token_secret_at_startup = true

# 是否在用户请求目录列表时隐藏无权访问的目录或文件？
# 设置为 true 来启用，建议开启。
# 未来本设置将移动至策略。
hide_when_no_access = true

# 是否为各类型的登录失败返回详细的错误信息？
show_login_fail_details = false

[database]

# 使用的数据库类型，目前支持 sqlite3 与 mysql
use_database = "sqlite3"

# 如果使用 sqlite3, 指定其文件名
sqlite3_db_name = "general.db"

### 配置 MySQL
mysql_host = ""
mysql_port = 3306

mysql_username = ""
mysql_password = ""

# 指定使用的数据库
mysql_db_name = ""

[cron]
do_clean_job_interval = 600
# 间隔多少秒执行过期文件的删除任务？

do_clear_cache_job_interval = 60
# 定期清理不再需要的传输临时文件所间隔的时间。单位为秒。

[debug]
debug = true

[exit]
wait_sec = 3